version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: georgesgil
      POSTGRES_PASSWORD: 1182363
      POSTGRES_DB: georgesgil
    ports:
      - "5432:5433"  # Map external port 5432 to internal port 5433 in the container

  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
